name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: bash provide rights
        run: /bin/bash/ chmod +x gradlew
             sed $'s/\r$//' ./install.sh > ./install.Unix.sh



      - name: Build with Gradle
        run: ./gradlew build
